# Generated by Django 3.2.8 on 2022-08-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220809_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='user',
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='info',
            field=models.CharField(default='default', max_length=300),
        ),
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.CharField(default='default', max_length=300),
        ),
    ]
