# Generated by Django 3.2.8 on 2022-08-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_info_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='user',
        ),
    ]
