# Generated by Django 3.2.8 on 2022-08-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.info'),
        ),
    ]
